### PR TITLE
to fix the NPE if TransactionCoordinator disabled

### LINKED ISSUE #397: [BUG] fetch message get an NPE if TransactionCoordinator disabled
**Describe the bug**
fetch message get an error if TransactionCoordinator disabled

**To Reproduce**
1. disable TransactionCoordinator by `enableTransactionCoordinator=false`
2. consume the messages by librdkafka client without `isolation.level=read_uncommitted` property.
3. See error

**Expected behavior**
consume correctly.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by dockerzhang**
fix #397

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java [hunk 1]
```diff
@@ -225,12 +225,8 @@ private void readMessagesInternal(KafkaHeaderAndRequest fetch,
...
 
                         if (entries != null && !entries.isEmpty()) {
-                            if (isolationLevel.equals(IsolationLevel.READ_UNCOMMITTED)) {
-                                entryList.addAll(entries);
-                                entriesRead.addAndGet(entries.size());
-                                bytesRead.addAndGet(entryList.stream().parallel().map(e ->
-                                        e.getLength()).reduce(0, Integer::sum));
-                            } else {
+                            if (requestHandler.getKafkaConfig().isEnableTransactionCoordinator()
+                                    && isolationLevel.equals(IsolationLevel.READ_COMMITTED)) {
```
Comment (hangc0276) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java:229]: should check `tc != null` ?

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
Please apply following diff and retry

```diff
diff --git a/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
index 3192802..911506b 100644
--- a/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
+++ b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessageFetchContext.java
@@ -31,6 +31,7 @@ import java.util.List;
 import java.util.Map;
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.ExecutionException;
 import java.util.concurrent.atomic.AtomicInteger;
 import java.util.stream.Collectors;
 import java.util.stream.StreamSupport;
@@ -251,7 +252,7 @@ public final class MessageFetchContext {
                                         fetch.getHeader(), kafkaTopic.toString(), entryList.size());
                             }
                         }
-                    } catch (Exception e) {
+                    } catch (InterruptedException | ExecutionException e) {
                         // readEntry.get failed because of readEntriesFailed. return error for this partition
                         log.error("Request {}: Failed readEntry.get for topic: {}. ",
                             fetch.getHeader(), kafkaTopic, e);
```

**Comment by dockerzhang** [comment]
@BewareMyPower  there are too many lines in ` try catch` for the spotbugs.
