### PR TITLE
fix issue #252 bundle unload bug

### LINKED ISSUE #252: [BUG] testMutiBrokerUnloadReload cannot pass
**Describe the bug**
We disabled the DistributedClusterTest in #207 because these tests cannot pass in CI environment though they can pass in local environment. The track issue is #184 .

However, I found the `testMutiBrokerUnloadReload` cannot pass even in local environment. The other two tests of DistributedClusterTest work well.

**To Reproduce**

```bash
$ mvn clean install -DskipTests
$ mvn test '-Dtest=DistributedClusterTest#testMutiBrokerUnloadReload' -pl tests
```

Then the test timed out:

```
[ERROR] testMutiBrokerUnloadReload(io.streamnative.pulsar.handlers.kop.DistributedClusterTest)  Time elapsed: 30.013 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method io.streamnative.pulsar.handlers.kop.DistributedClusterTest.testMutiBrokerUnloadReload() didn't finish within the time-out 30000
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:299)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1247)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1187)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.kafkaConsumeCommitMessage(DistributedClusterTest.java:237)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.testMutiBrokerUnloadReload(DistributedClusterTest.java:447)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
`testMutiBrokerUnloadReload` should pass.

**Additional context**
The issue seems to be introduced from #193 , see following two commits:

```
d684f4bd295ed686aa6c6f371864f29f91c02e00 (HEAD -> upstream-master) remove unnecessary register producer (#193)
57a3cac44e55b0cb2c5d881cfe3db250a001c721 Add Kafka version coverage tests (#196)
```

When I reset to 57a3cac and run test again, it succeed.

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #252 

### Motivation
When bundle unload triggered, the `consumerTopicManagers` cache won't be evicted and it will return the old `KafkaTopicConsumerManager` instance in the next fetch request handle. However, after bundle unload, the producer/consumer/managedLedger of topics in related bundle will be closed. If we use old  `KafkaTopicConsumerManager` instance to read messages, it will return `managedLedger has been closed` exception.

### Changes
1. Change `consumerTopicManagers`, `topics`, `references` map to static attribute ConcurrentHashMap.
2. Evict related cache information for topics whose bundle trigged unload.
3. Turn on `DistributedClusterTest `.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by BewareMyPower** [comment]
@hangc0276 Could you take a look at the test failure? It looks like the test is still unstable after the change. I think it may not be caused by the uncleaned static cache.

**Comment by hangc0276** [comment]
> @hangc0276 Could you take a look at the test failure? It looks like the test is still unstable after the change. I think it may not be caused by the uncleaned static cache.

@BewareMyPower OK, maybe there are other bugs to cause this problem, it looks like caused by loadbalance, i will address it these days.

File: tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java [hunk 1]
```diff
@@ -298,19 +297,14 @@ public void testMutiBrokerAndCoordinator() throws Exception {
         // 1. produce message with Kafka producer.
         int totalMsgs = 50;
         String messageStrPrefix = "Message_Kop_KafkaProduceKafkaConsume_" + partitionNumber + "_";
-        @Cleanup
```
Comment (BewareMyPower) [inline tests/src/test/java/io/streamnative/pulsar/handlers/kop/DistributedClusterTest.java:301]: Could you explain why remove the `@Cleanup` here? Did it affect the tests?

**Comment by hangc0276** [comment]
When run ``, it will block in publishMessages, and in the retry round, also blocked.
image

The code of `ManagedLedgerImpl.java` as follow:
```
public void asyncAddEntry(ByteBuf buffer, int numberOfMessages, AddEntryCallback callback, Object ctx) {
        log.info("[hangc] start asyncAddEntry v1...");
        if (log.isDebugEnabled()) {
            log.debug("[{}] asyncAddEntry size={} state={}", name, buffer.readableBytes(), state);
        }

        OpAddEntry addOperation = OpAddEntry.create(this, buffer, numberOfMessages, callback, ctx);

        log.info("[hangc] start execute name: {}", name);
        // Jump to specific thread to avoid contention from writers writing from different threads
        executor.executeOrdered(name, safeRun(() -> log.info("pre exec...")));
        executor.executeOrdered(name, safeRun(() -> {
            log.info("[hangc] enter thread exec internalAsyncAddEntry...");
            internalAsyncAddEntry(addOperation);
        }));
```

**Comment by BewareMyPower** [comment]
@hangc0276 Could you take a look at the failed `testOneBrokerShutdown`?

**Review by BewareMyPower — APPROVED** [review]
