### PR TITLE
Use setMetadataFromEntryData API to retrieve offset

### LINKED ISSUE #332: [BUG] Offset in send callback is not continuous when batching is enabled
**Describe the bug**
#296 implemented continuous offset, but in producer's send callback, the offset is not continuous when batching is enabled.

**To Reproduce**

Modify `KafkaRequestHandlerTest#testProduceCallbck` to following code and rerun.

```java
    public void testProduceCallback() throws Exception {
        final String topic = "test-produce-callback";
        final int numMessages = 20;
        final String messagePrefix = "msg-";

        final Properties props = new Properties();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:" + getKafkaBrokerPort());
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, IntegerSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.BATCH_SIZE_CONFIG, "100"); // avoid all messages being in the same batch

        @Cleanup
        KafkaProducer<Integer, String> producer = new KafkaProducer<>(props);

        Map<Integer, Long> indexToOffset = new ConcurrentHashMap<>();
        final CountDownLatch latch = new CountDownLatch(numMessages);
        for (int i = 0; i < numMessages; i++) {
            final int index = i;
            producer.send(new ProducerRecord<>(topic, i, messagePrefix + i), (recordMetadata, e) -> {
                if (e != null) {
                    log.error("Failed to send {}: {}", index, e);
                    fail("Failed to send " + index + ": " + e.getMessage());
                }
                assertEquals(recordMetadata.topic(), topic);
                assertEquals(recordMetadata.partition(), 0);
                indexToOffset.put(index, recordMetadata.offset());
                latch.countDown();
            }); // asynchronous send
        }
        latch.await();
        indexToOffset.forEach((index, offset) -> {
            log.info("{} => {} (delta = {})", index, offset, offset - index);
        });
```

The output:

```
1 => 10 (delta = 9)
2 => 9 (delta = 7)
3 => 10 (delta = 7)
4 => 9 (delta = 5)
5 => 10 (delta = 5)
6 => 9 (delta = 3)
7 => 10 (delta = 3)
8 => 9 (delta = 1)
9 => 10 (delta = 1)
10 => 19 (delta = 9)
11 => 20 (delta = 9)
12 => 19 (delta = 7)
13 => 20 (delta = 7)
14 => 19 (delta = 5)
15 => 20 (delta = 5)
16 => 19 (delta = 3)
17 => 20 (delta = 3)
18 => 19 (delta = 1)
19 => 20 (delta = 1)
```

We can see the offset is not continuous, even not monodic increasing. And the first offset is not zero.

However, if we use synchronous send, i.e. `producer.send(/* ... */).get()`, the first offset will be 0, and the offset will be continuous.

**Expected behavior**
The offset in producer's send callback is continuous.

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #332 

The offset in produce callback may be not accurate when the messages are sent in batch, see https://github.com/streamnative/kop/issues/332#issuecomment-762712235 for detail explanation.

Since https://github.com/apache/pulsar/pull/9257 introduced a new API that supports fetching some metadata from the entry data, we can use this API to get the accurate offset.

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java [hunk 1]
```diff
@@ -33,7 +34,23 @@
...
+
+    @Override
+    public void setMetadataFromEntryData(ByteBuf entryData) {
+        try {
+            final BrokerEntryMetadata brokerEntryMetadata = Commands.peekBrokerEntryMetadataIfExist(entryData);
+            if (brokerEntryMetadata == null) {
+                throw new IllegalStateException(
+                        "There's no BrokerEntryData, check if your broker configured brokerEntryMetadataInterceptors");
+            }
+            baseOffset = brokerEntryMetadata.getIndex() - (numberOfMessages - 1);
```
Comment (jiazhai) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java:47]: There may be cases, that entryMetdataEnabled, but Index not used.

**Review by jiazhai — APPROVED** [review]
overall lgtm. left a minor comments

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java (hunk 1 above)
Comment (jiazhai) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/MessagePublishContext.java:47]: There maybe cases that  brokerEntryMetadata enabled, but index not used, and only contains default value. we should handle this case？

**Comment by BewareMyPower** [comment]
It looks like `SchemaRegistryTest.testAvroProduceAndConsume` always failed but it succeeded in my local env. I'll dig into the reason later.
