### PR TITLE
Fix the findBroker method may hang

### LINKED ISSUE #678: [Flaky-test] DistributedClusterTest.testMutiBrokerUnloadReload
`DistributedClusterTest` is flaky. The `testMutiBrokerUnloadReload` test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/3396339243?check_suite_focus=true#step:5:167)

```
Error:  testMutiBrokerUnloadReload(io.streamnative.pulsar.handlers.kop.DistributedClusterTest)  Time elapsed: 11.62 s  <<< FAILURE!
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for kopMutiBrokerUnloadReload10-0: 10001 ms has passed since batch creation plus linger time
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.valueOrError(FutureRecordMetadata.java:94)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:64)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:29)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.kafkaPublishMessage(DistributedClusterTest.java:197)
	at io.streamnative.pulsar.handlers.kop.DistributedClusterTest.testMutiBrokerUnloadReload(DistributedClusterTest.java:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for kopMutiBrokerUnloadReload10-0: 10001 ms has passed since batch creation plus linger time

```

### LINKED ISSUE #682: [BUG] testMutiBrokerUnloadReload is easy to fail if it ran after other tests
**Describe the bug**
See https://github.com/streamnative/kop/pull/646#issuecomment-899075427 for the context. It may be caused by the existing bug of KoP or the cleanup method of the test.

**To Reproduce**
Run the whole `DistributedClusterTest` or add `invocationCount` to `testMutiBrokerUnloadReload` like

```java
    @Test(timeOut = 30000, invocationCount = 10)
```

In my local env, there're 7 (of 10) times that it failed. Once it failed, the followed tests all failed because they reuse the same topic name. It looks like the topic is not available after that.

**Expected behavior**
The test should pass even it ran after other tests.

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes #682

## Motivation
The test unit `DistributedClusterTest#testMultiBrokerUnloadReload()` is flaky. 
If the`topicManager.getTopicBroker(topic.toString())` method has exception,  the `thenCompose` supplied function will never called, In this case `stringOptional` is null, will cause `NullPointerException`. 

See docs in : https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html#thenCompose-java.util.function.Function-

## Modification
Use `thenApply` to replase `thenCompose`

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java [hunk 1]
```diff
@@ -2258,34 +2258,35 @@ protected boolean isTransactionTopic(String topic) {
...
-            .whenComplete((stringOptional, throwable) -> {
-                if (!stringOptional.isPresent() || throwable != null) {
-                    log.error("Not get advertise data for Kafka topic:{}. throwable: [{}]",
-                        topic, throwable.getMessage());
-                    KafkaTopicManager.removeTopicManagerCache(topic.toString());
-                    returnFuture.complete(null);
-                    return;
-                }
+                .thenCompose(address -> getProtocolDataToAdvertise(address, topic))
+                .whenComplete((stringOptional, throwable) -> {
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java:2262]: Combining `thenCompose` and `whenComplete` is not a good way to handle future. The null completed value is confused that it looks like a `Optional<T>` future might complete with null value.

It's better to combine `thenXXX` with `exceptionally`, with could handle all possible exceptions in previous chains.

```java
future.thenApply(/* block 1 */).thenApply(/* block 2 */).exceptionally(e -> {
    // e could be from block 1 or block 2 or even future itself
    // if e was thrown from block 1 or block 2, e's type is CompletionException, e.getCause() is the actual exception
    return null;
});
```

`whenComplete` is mostly used when you just need a callback for a future.

Comment (Demogorgon314) [reply kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java]: Good suggestion. I already used `thenApply` to replase `thenCompose` now. PTAL.

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
Approved. You can update your PR description and merge it.
