### PR TITLE
[BUG#1500] Cannot submit offset correctly

### LINKED ISSUE #1500: [BUG] Cannot submit offset correctly
**Describe the bug**
81ad161cc951006f0395748d9fa2270

`                    long baseOffset = MessageMetadataUtils.getMockOffset(
                        lastMessageId.getLedgerId(),
                        lastMessageId.getEntryId()
                    );`
The baseOffset is not monotonically increasing, consumer cannot submit offset correctly.
The offset can be detected incorrectly through Kafka Exporter.

**To Reproduce**
Normal consumption messages can reproduce the bug.

### PR DESCRIPTION
**Pull request by lwclover**
Fixes #1500 

### Motivation

The baseOffset is not monotonically increasing, consumer cannot submit offset correctly.

### Modifications

When the offset is submitted, the increasing judgment mode of baseOffset is changed

### Verifying this change

This change is already covered by existing tests.

1.passed GroupMetadataManagerTest
2.passed GroupMetadataTest

### CODE REVIEW

**Comment by BewareMyPower** [comment]
Could you fill the PR description with the template [here](https://github.com/streamnative/kop/blob/master/.github/PULL_REQUEST_TEMPLATE.md)? You should have seen the template when you open a PR like

image

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Could you add a test to avoid the regression? It would be better to add a test that shows how to reproduce the bug in #1500.

**Comment by lwclover** [comment]
> Could you fill the PR description with the template [here](https://github.com/streamnative/kop/blob/master/.github/PULL_REQUEST_TEMPLATE.md)? You should have seen the template when you open a PR like
> 
> image
> 
> In addition, you should sign the CLA.

Signed

**Comment by BewareMyPower** [comment]
The existing tests can only verify `getMockOffset`, but it cannot verify the case when consumer failed to commit offset without this patch.

**Comment by lwclover** [comment]
> The existing tests can only verify `getMockOffset`, but it cannot verify the case when consumer failed to commit offset without this patch.

OK, I will add a test case to cover the situation.

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java [hunk 1]
```diff
@@ -166,11 +167,22 @@ public static class GroupSummary {
      */
     @Data
     static class CommitRecordMetadataAndOffset {
-        private final Optional<Long> appendedBatchOffset;
+        private final Optional<String> appendedBatchOffset;
```
Comment (Demogorgon314) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java:170]: I'm more prefer to use `org.apache.bookkeeper.mledger.impl.PositionImpl` in here. 

Then we can use `this.appendedBatchOffset.get().compareTo(that.appendedBatchOffset.get()) < 0` to compare this two position.

**Review by Demogorgon314 — CHANGES_REQUESTED** [review]

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java (hunk 1 above)
Comment (lwclover) [reply kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java]: You are right

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java [hunk 2]
```diff
@@ -166,11 +167,11 @@ public static class GroupSummary {
      */
     @Data
     static class CommitRecordMetadataAndOffset {
-        private final Optional<Long> appendedBatchOffset;
+        private final Optional<PositionImpl> appendedBatchOffset;
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java:170]: It's better to rename it with `appendedBatchPosition` since it doesn't represent an offset anymore.

Comment (lwclover) [reply kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/coordinator/group/GroupMetadata.java]: renamed

**Review by Demogorgon314 — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]
