### PR TITLE
fix direct memory leak bug

### LINKED ISSUE #442: [BUG] Encounter corrupted messages after recovered from an OOM
**Describe the bug**
After broker restarted from an OOM, the `KafkaEntryFormatter#decode` could throw an exception.

```
16:17:54.918 [bookkeeper-ml-workers-OrderedExecutor-4-0] ERROR org.apache.pulsar.common.protocol.Commands - [null] [0] Failed to parse message metadata
java.lang.IllegalArgumentException: Invalid unknonwn tag type: 7
    at org.apache.pulsar.common.api.proto.LightProtoCodec.skipUnknownField(LightProtoCodec.java:270) ~[org.apache.pulsar-pulsar-common-2.8.0-rc-202102252222.jar:2.8.0-rc-202102252222]
    at org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1370) ~[org.apache.pulsar-pulsar-common-2.8.0-rc-202102252222.jar:2.8.0-rc-202102252222]
    at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:426) ~[org.apache.pulsar-pulsar-common-2.8.0-rc-202102252222.jar:2.8.0-rc-202102252222]
    at org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:416) ~[org.apache.pulsar-pulsar-common-2.8.0-rc-202102252222.jar:2.8.0-rc-202102252222]
    at org.apache.pulsar.common.protocol.Commands.peekMessageMetadata(Commands.java:1668) ~[org.apache.pulsar-pulsar-common-2.8.0-rc-202102252222.jar:2.8.0-rc-202102252222]
    at io.streamnative.pulsar.handlers.kop.utils.MessageIdUtils.peekBaseOffsetFromEntry(MessageIdUtils.java:114) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.format.KafkaEntryFormatter.lambda$decode$0(KafkaEntryFormatter.java:52) ~[?:?]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952) ~[?:?]
    at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926) ~[?:?]
    at java.util.stream.AbstractTask.compute(AbstractTask.java:327) ~[?:?]
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
    at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) ~[?:?]
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.format.KafkaEntryFormatter.decode(KafkaEntryFormatter.java:62) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.MessageFetchContext.lambda$null$12(MessageFetchContext.java:371) ~[?:?]
    at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4864) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.MessageFetchContext.lambda$readMessagesInternal$13(MessageFetchContext.java:318) ~[?:?]
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
    at io.streamnative.pulsar.handlers.kop.MessageFetchContext$2.readEntriesComplete(MessageFetchContext.java:458) ~[?:?]
```

In addition, there's another unexcepted error:

```
16:18:13.011 [AsyncHttpClient-54-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [persistent://public/default/test-topic-FYeWwgs-0000-partition-0] failed get pulsar address, returned null.
16:18:13.011 [AsyncHttpClient-54-1] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Not get advertise data for Kafka topic:persistent://public/default/test-topic-FYeWwgs-0000-partition-0. throwable
```

It looks like the topic was deleted.

**To Reproduce**
Run 2 producers and 2 consumers for a 3 nodes KoP cluster with the 200000 messages producer rate and each message's size is 1 KB.

**Expected behavior**
We should handle the exception from `decode` at least.

**Screenshots**
image

image

**Additional context**

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #442 

### Modification
1. Add NPE check for `peekOffsetFromEntry` and `peekBaseOffsetFromEntry`
2. Auto skip fetched exception entry in decode stage to avoid direct memory leak.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java [hunk 1]
```diff
@@ -93,7 +95,7 @@ public void readEntryComplete(Entry entry, Object ctx) {
         return future;
     }
 
-    public static PositionImpl getPositionForOffset(ManagedLedger managedLedger, Long offset) {
+    public static PositionImpl getPositionForOffset(ManagedLedger managedLedger, Long offset) throws RuntimeException {
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java:98]: Could you use a derived exception type instead of `RuntimeException`? Normally `RuntimeException` is an unchecked exception. I think it's better to create an exception that derives from `Exception` and throw it in `catch` clause.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

**Comment by BewareMyPower** [comment]
Since it could be conflict with #556, I think you can wait until #556 is merged and fix this PR after that.

**Comment by jiazhai** [comment]
@hangc0276 Would you please help update with latest master code?

**Comment by hangc0276** [comment]
> @hangc0276 Would you please help update with latest master code?

OK，I will update the code today.

**Comment by BewareMyPower** [comment]
Please fix the spotbugs check

> Medium: Exception is caught when Exception is not thrown in io.streamnative.pulsar.handlers.kop.format.PulsarEntryFormatter.lambda$decode$3(ByteBuffer, byte, List, Entry) [io.streamnative.pulsar.handlers.kop.format.PulsarEntryFormatter] At PulsarEntryFormatter.java:[line 228] REC_CATCH_EXCEPTION

And it's better not to use `throws Exception` directly. Add a new exception type that derived from `Exception`.

**Comment by BewareMyPower** [comment]
I also noticed `OffsetResetTest#testLessThanStartOffset` is very easy to fail. If it's convenient, you can mark it as `@Ignore` in this PR so that we don't need a new PR to fix it. BTW, this test should not be passed now.

**Comment by hangc0276** [comment]
> I also noticed `OffsetResetTest#testLessThanStartOffset` is very easy to fail. If it's convenient, you can mark it as `@Ignore` in this PR so that we don't need a new PR to fix it. BTW, this test should not be passed now.

@BewareMyPower I have update the code, PTAL, thanks.

**Review by BewareMyPower — APPROVED** [review]
