### PR TITLE
remove unnecessary topics cache for Topic Manager

### LINKED ISSUE #266: [BUG] redundant topic cache for Topic Manager
**Describe the bug**
`topics` in `KafkaTopicManager` will cache `PersistentTopic` by `brokerService.getTopic`, it's unnecessary because `PersistentTopic` is cached in `brokerService.getTopic`. we should remove it to avoid getting a `null` topic.

### PR DESCRIPTION
**Pull request by dockerzhang**
fixes #266 
`topics` in `KafkaTopicManager` will cache `PersistentTopic` by `brokerService.getTopic`, it's unnecessary because `PersistentTopic` is cached in `brokerService.getTopic`. we should remove it to avoid getting a `null` topic.

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java [hunk 1]
```diff
@@ -358,22 +330,6 @@ public synchronized void close() {
                 manager.get().close();
             }
             consumerTopicManagers.clear();
-
-            for (Map.Entry<String, CompletableFuture<PersistentTopic>> entry : topics.entrySet()) {
-                String topicName = entry.getKey();
-                removeTopicManagerCache(topicName);
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java:364]: Should `removeTopicManagerCache` be retained?

**Comment by jiazhai** [comment]
@dockerzhang Thanks for the change. Would you please help add the dedicated test cases to test the new code path? 
So the code could be protected by the test cases.

**Comment by dockerzhang** [comment]
@jiazhai there is existed `KafkaTopicManager` UT for this PR.
@BewareMyPower the newest topic cache only serve to remove the producer after the connection close.

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java [hunk 2]
```diff
@@ -371,8 +347,8 @@ public synchronized void close() {
                     topicFuture.get().removeProducer(references.get(topicName));
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java:347]: `topicFuture.get()` needs a null check because the topic future that was put to `topics` may complete with null.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
LGTM. PTAL again @jiazhai
