### PR TITLE
Fix list offsets response wrong result

### LINKED ISSUE #1444: Flaky-test: KafkaMessageOrderKafkaTest.testKafkaProduceMessageOrder
KafkaMessageOrderKafkaTest is flaky. The testKafkaProduceMessageOrder test method fails sporadically.

[example failure](https://github.com/streamnative/kop/runs/7738563391?check_suite_focus=true#step:12:207)

```
Error:  testKafkaProduceMessageOrder(io.streamnative.pulsar.handlers.kop.KafkaMessageOrderKafkaTest)  Time elapsed: 0.194 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [19]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at io.streamnative.pulsar.handlers.kop.KafkaMessageOrderTestBase.testKafkaProduceMessageOrder(KafkaMessageOrderTestBase.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes #1444 #1168

### Motivation

Currently, the list offset operation might return the wrong offset.
Because when `position > lac`, we will try to get the latest offset from `AppendIndexMetadataInterceptor`,
However, if we have a producer produce messages to the current `ManagedLedger`,
the latest offset might be wrong since the `AppendIndexMetadataInterceptor#index` is increased before the ledger persistence.

When this case happens, we might lose the first few pieces of messages, since the Kafka client will reset offset in the beginning.

### Modifications

Make the `position > lac` condition return offset 0.

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java [hunk 1]
```diff
@@ -162,18 +162,21 @@ public void testKafkaProduceMessageOrder(int batchSize) throws Exception {
...
-                        assertEquals(record.key().intValue(), i);
-                        i++;
+                for (ConsumerRecord<Integer, String> record : records) {
+                    if (log.isDebugEnabled()) {
+                        log.debug("Kafka consumer get i: {} offset: {}, message: {}, key: {}",
+                                i, record.offset(), record.value(), record.key());
                     }
-                } else {
-                    i += records.count();
+                    receivedKeys[i++] = record.key();
```
Comment (BewareMyPower) [inline tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java:173]: If the message lost, the loop would never stop and the test would fail with timeout so that we cannot see the received keys. I think we can add a timeout for the whole for loop. A simple way is to increase the poll timeout (to 5 seconds for example) and break the loop if `records` is empty.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java (hunk 1 above)
Comment (Demogorgon314) [reply tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java:173]: Good point.

Comment (Demogorgon314) [reply tests/src/test/java/io/streamnative/pulsar/handlers/kop/KafkaMessageOrderTestBase.java:173]: Actually, we can use the debug log to see the received keys, if the message lost.

**Review by BewareMyPower — APPROVED** [review]
