### PR TITLE
[fix] not respone for PRODUCE when acks=0

### LINKED ISSUE #1875: [BUG] When the Kafka Producer sets acks=0 to send messages to KoP, an error will be throw
**Describe the bug**
When the Kafka Producer sets acks=0 to send messages to KoP, an error will be thrown. The exception message is as follows:
```
java.lang.IllegalStateException: There are no in-flight requests for node
```
image

- kop version 2.10.3 （This can also be reproduced when using kop 2.9.x）
- kafka client version 2.5.0

The above phenomenon can also be consistently reproduced when sending messages using kafka bin/./kafka-producer-perf-test.sh.
```
./kafka-producer-perf-test.sh --topic perf-test-rep2-p30 \
--num-records 10 \
--record-size 1024 \
--throughput 1 \
--producer-props \
acks=0 \
bootstrap.servers={}
```

- kafka version: kafka_2.11-2.4.1/bin

**To Reproduce**
1. download kafka_2.11-2.4.1 and extract  `wget https://archive.apache.org/dist/kafka/2.4.1/kafka_2.11-2.4.1.tgz`
2. enter the bin directory, and execute the corresponding script.
```
./kafka-producer-perf-test.sh --topic perf-test-rep2-p30 \
--num-records 10 \
--record-size 1024 \
--throughput 1 \
--producer-props \
acks=0 \
bootstrap.servers={}
```

**Expected behavior**
no error thrown

### PR DESCRIPTION
**Pull request by SunDapeng1**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #1875

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

When the Kafka Producer sets acks=0 to send messages to KoP, an error will be throw

### Modifications

not respone for PRODUCE when acks=0

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java [hunk 1]
```diff
@@ -2409,6 +2411,7 @@ protected void handleWriteTxnMarkers(KafkaHeaderAndRequest kafkaHeaderAndRequest
                     ctx);
             getReplicaManager().appendRecords(
                     kafkaConfig.getRequestTimeoutMs(),
+                    kafkaConfig.getRequiredAcks(),
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java:2414]: We don't need to add a server-side config for it. Just pass 1 because we should not skip the callback of `partitionLog#addPartitionResponse` here.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Could you also add a unit test to verify the change?

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java (hunk 1 above)
Comment (SunDapeng1) [reply kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java:2414]: sorry,  I'll submit the unit test later and  pass 1 here.
