### PR TITLE
[Transaction] Able to disable transaction coordinator

### LINKED ISSUE #1090: [BUG] Kafka transaction coordinator unable to disable
**Describe the bug**

Currently, even if we config `kafkaTransactionCoordinatorEnabled=false`, the Kafka transaction coordinator is still started.

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes  #1090

### Motivation
Currently, even if we config kafkaTransactionCoordinatorEnabled=false, the Kafka transaction coordinator is still started.
It happened when the broker has a consumer fetch message.

### Modifications
When `kafkaTransactionCoordinatorEnabled = false`, ensure the transaction coordinator don't start.

### CODE REVIEW

File: kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java [hunk 1]
```diff
@@ -267,7 +267,10 @@ public GroupCoordinator getGroupCoordinator() {
     }
 
     public TransactionCoordinator getTransactionCoordinator() {
-        return tenantContextManager.getTransactionCoordinator(getCurrentTenant());
+        if (kafkaConfig.isKafkaTransactionCoordinatorEnabled()) {
+            return tenantContextManager.getTransactionCoordinator(getCurrentTenant());
+        }
+        return null;
```
Comment (BewareMyPower) [inline kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java:273]: It's better to throw an exception here rather than returning a `null` value. Otherwise, the caller would have to call `throwIfTransactionCoordinatorDisabled` each time before `getTransactionCoordinator` is called.

Comment (Demogorgon314) [reply kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaRequestHandler.java]: Good idea.

**Review by BewareMyPower — APPROVED** [review]
